[package]
name = "libcapstone-sys"
version = "0.3.2"
authors = ["th0rex"]
build = "build.rs"
description = "Rust bindings to the capstone engine"
license = "MIT"
repository = "https://github.com/th0rex/libcapstone-sys"

[dependencies]

[build-dependencies]
bindgen = "0.22.1"
